name: "Test chromedriver"
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    branches:
      - '*'
    paths:
      - '**'
      - '!*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
        echo "CHROMEDRIVER_VERSION=$(curl --location --fail --retry 10 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})" >> $GITHUB_ENV
    - uses: ./
      with:
        chromedriver-version: ${{ env.CHROMEDRIVER_VERSION }}
    - name: setup
      run: |
        google-chrome --version
        sudo pip3 install selenium
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # disable headless mode
        python3 $GITHUB_WORKSPACE/__tests__/chromedriver.py

  test_default_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
    - name: setup
      run: |
        google-chrome --version
        sudo pip3 install selenium
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # disable headless mode
        python3 $GITHUB_WORKSPACE/__tests__/chromedriver.py
